telegram:
  bot_token: 
  drop_updates: 
  webhook: 
  webhook_url: 
  webhook_port: 
  webhook_cert_path: 
  sudo_users:
    - 123
    - 456

database:
  schema: 

valkey:
  enabled: 
  host: 
  port: 
  db: 
  ttl: 
  screenshot_cache: 

bubblemaps:
  supported_chains:
    - eth
    - bsc
    - ftm
    - avax
    - cro
    - arbi
    - poly
    - base
    - sol
    - sonic
  api:
    base_api_url: https://api-legacy.bubblemaps.io/map-data
    map_availability_url: https://api-legacy.bubblemaps.io/map-availability
    map_metadata_url: https://api-legacy.bubblemaps.io/map-metadata?chain={chain}&token={token}
    iframe_template_url: https://app.bubblemaps.io/{chain}/token/{token}
